window.ISLAMIC_HABITS_CONFIG = {
  duaPrice: "Free",
  stripePaymentLinks: { english: "" },
  duaDownloadLinks: { english: "./downloads/100-hours-dua-practice-english.pdf" },
  adsenseClient: "",
  googleAdsConversionId: "AW-18157183110",
  googleAdsConversionLabel: "",
};

(() => {
  const id = "circle3";
  const styleId = "circle3-triadic-style";

  const addStyle = () => {
    if (document.getElementById(styleId)) return;
    const style = document.createElement("style");
    style.id = styleId;
    style.textContent = `
      .circle3{margin:0 clamp(18px,5vw,72px);padding:76px 0;scroll-margin-top:96px;position:relative;isolation:isolate}.circle3:before{position:absolute;inset:36px -4vw auto;z-index:-1;height:560px;border:1px solid rgba(246,242,232,.06);border-radius:30px;background:radial-gradient(circle at 18% 14%,rgba(240,191,85,.16),transparent 30%),radial-gradient(circle at 80% 22%,rgba(91,214,232,.15),transparent 26%),rgba(5,14,12,.3);content:""}
      .circle3-grid{display:grid;grid-template-columns:minmax(320px,.92fr) minmax(320px,1.08fr);gap:18px;align-items:stretch}.circle3-hero,.circle3-chat,.circle3-pillars article,.circle3-saas-grid article,.circle3-note,.circle3-story-card,.circle3-system,.circle3-activation-visual,.circle3-activation-copy,.circle3-live-copy,.circle3-live-script,.circle3-feature-board article,.circle3-matrix article,.circle3-infra article,.circle3-identity article,.circle3-room-types,.circle3-room-types article,.circle3-roadmap{border:1px solid var(--line);background:var(--panel);box-shadow:var(--shadow)}
      .circle3-hero{display:grid;gap:24px;align-content:space-between;min-height:560px;border-radius:26px;padding:clamp(22px,4vw,36px);overflow:hidden;background:linear-gradient(145deg,rgba(66,209,155,.1),rgba(91,214,232,.07)),var(--panel)}.circle3-hero h3{max-width:560px;margin:0 0 12px;font-size:clamp(1.8rem,3.2vw,3.1rem);line-height:1.02}.circle3-orbit{position:relative;min-height:300px;border:1px solid rgba(246,242,232,.1);border-radius:24px;overflow:hidden;background:radial-gradient(circle at 50% 50%,rgba(240,191,85,.18),transparent 26%),radial-gradient(circle at 50% 50%,rgba(66,209,155,.14),transparent 52%),rgba(5,14,12,.4)}.circle3-orbit:before,.circle3-orbit:after{position:absolute;inset:44px;border:1px solid rgba(246,242,232,.16);border-radius:50%;content:""}.circle3-orbit:after{inset:82px;border-color:rgba(91,214,232,.22)}.circle3-orbit i{position:absolute;left:50%;top:50%;width:78px;height:78px;border-radius:50%;background:linear-gradient(135deg,rgba(246,242,232,.08),rgba(240,191,85,.18)),rgba(5,14,12,.88);box-shadow:0 0 46px rgba(240,191,85,.22);transform:translate(-50%,-50%)}.circle3-orbit i:before{position:absolute;inset:21px;border:3px solid var(--gold);border-top:0;border-radius:0 0 18px 18px;content:""}
      .circle-person{position:absolute;z-index:2;display:grid;place-items:center;width:104px;height:104px;border:1px solid rgba(246,242,232,.18);border-radius:50%;color:var(--soft);background:radial-gradient(circle at 35% 25%,rgba(246,242,232,.2),transparent 28%),rgba(6,38,33,.9);font-family:var(--font-display);font-size:.84rem;text-align:center}.circle-person b{max-width:82px}.circle-person.partner{left:8%;bottom:14%}.circle-person.friend{right:8%;bottom:14%}.circle-person.guide{left:50%;top:6%;color:#07100e;background:radial-gradient(circle at 35% 25%,rgba(255,255,255,.34),transparent 28%),linear-gradient(135deg,var(--gold),#f7dd91);transform:translateX(-50%)}
      .circle3-chat{display:grid;align-items:center;border-radius:26px;padding:clamp(20px,4vw,34px);background:radial-gradient(circle at 88% 8%,rgba(91,214,232,.18),transparent 28%),rgba(5,14,12,.7)}.circle3-window{display:grid;gap:14px;border:8px solid #07100e;border-radius:34px;padding:18px;background:linear-gradient(180deg,rgba(6,47,41,.96),rgba(3,34,30,.98));box-shadow:0 24px 50px rgba(0,0,0,.24)}.circle3-top,.circle3-strip{display:flex;gap:10px;align-items:center;justify-content:space-between;border-radius:16px;padding:12px 14px;font-weight:900}.circle3-top{color:#07100e;background:linear-gradient(135deg,var(--emerald),var(--aqua))}.circle3-top strong{border-radius:999px;padding:5px 9px;background:rgba(255,255,255,.38)}.circle3-strip{color:var(--gold);background:rgba(240,191,85,.1)}.circle3-strip b{color:var(--soft);font-size:.78rem}.circle3-bubble{max-width:86%;border:1px solid rgba(246,242,232,.12);border-radius:18px;padding:14px;color:var(--soft);background:rgba(246,242,232,.08);line-height:1.45}.circle3-bubble small{display:block;margin-bottom:5px;color:var(--gold);font-weight:950}.circle3-bubble.member{justify-self:end;background:rgba(66,209,155,.12)}.circle3-bubble.silent{max-width:none;color:#07100e;background:rgba(246,242,232,.86)}.circle3-bubble.silent small{color:#00694c}
      .circle3-pillars,.circle3-feature-board,.circle3-identity{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:18px}.circle3-saas-grid,.circle3-matrix,.circle3-infra{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:12px}.circle3-deep{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.circle3-pillars article,.circle3-saas-grid article,.circle3-feature-board article,.circle3-matrix article,.circle3-infra article,.circle3-identity article,.circle3-story-card{display:grid;gap:10px;border-radius:18px;padding:18px}.circle3-pillars span,.circle3-identity span{display:inline-grid;place-items:center;width:42px;height:42px;border:1px solid rgba(240,191,85,.4);border-radius:14px;color:var(--gold);background:rgba(240,191,85,.1);font-weight:950}.circle3-identity span{border-color:rgba(91,214,232,.38);color:var(--aqua);background:rgba(91,214,232,.1)}.circle3-pillars h3,.circle3-saas-grid h3,.circle3-feature-board h3,.circle3-matrix h3,.circle3-infra h3,.circle3-identity h3{margin:0;font-size:1.12rem}.circle3-pillars p,.circle3-saas-grid li,.circle3-feature-board p,.circle3-matrix p,.circle3-infra p,.circle3-identity p{margin:0;color:var(--muted);font-size:.95rem}.circle3-saas-grid ul{display:grid;gap:8px;margin:0;padding-left:18px}.circle3-feature-board span{width:max-content;border-radius:999px;padding:6px 9px;color:#07100e;background:linear-gradient(135deg,var(--gold),var(--mint));font-size:.75rem;font-weight:950}
      .circle3-story-card{min-height:290px;border-radius:22px;padding:clamp(20px,3vw,28px);background:radial-gradient(circle at 12% 12%,rgba(240,191,85,.16),transparent 30%),var(--panel)}.circle3-story-card.accent{background:radial-gradient(circle at 88% 16%,rgba(66,209,155,.16),transparent 30%),var(--panel)}.circle3-story-card h3,.circle3-system-copy h3,.circle3-roadmap h3,.circle3-activation-copy h3,.circle3-live-copy h3{margin:0;font-size:clamp(1.45rem,2.7vw,2.55rem);line-height:1.05}.circle3-story-card p,.circle3-system-copy p,.circle3-roadmap p,.circle3-room-types p,.circle3-live-copy p,.circle3-live-script p{margin:0;color:var(--muted)}.circle3-tags{display:flex;flex-wrap:wrap;gap:8px;margin-top:auto}.circle3-tags span{border:1px solid rgba(246,242,232,.12);border-radius:999px;padding:8px 10px;color:var(--soft);background:rgba(246,242,232,.06);font-size:.82rem;font-weight:850}
      .circle3-system{display:grid;grid-template-columns:minmax(260px,.84fr) minmax(320px,1.16fr);gap:18px;align-items:stretch;margin-top:12px;border-radius:24px;padding:clamp(20px,3vw,30px);background:linear-gradient(135deg,rgba(66,209,155,.08),rgba(91,214,232,.06)),var(--panel)}.circle3-system-copy{display:grid;align-content:center;gap:12px}.circle3-flow{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.circle3-flow article{display:grid;gap:8px;border:1px solid rgba(246,242,232,.1);border-radius:18px;padding:16px;background:rgba(5,14,12,.34)}.circle3-flow strong{width:max-content;border-radius:999px;padding:6px 9px;color:#07100e;background:linear-gradient(135deg,var(--gold),var(--mint));font-size:.75rem;font-weight:950}.circle3-flow h4{margin:0}.circle3-flow p{margin:0;color:var(--muted);font-size:.92rem}
      .circle3-activation,.circle3-live-room{display:grid;grid-template-columns:minmax(300px,.92fr) minmax(320px,1.08fr);gap:18px;align-items:stretch;margin-top:12px}.circle3-activation-visual{position:relative;min-height:360px;border-radius:26px;overflow:hidden;background:radial-gradient(circle at 50% 50%,rgba(66,209,155,.18),transparent 30%),radial-gradient(circle at 50% 50%,rgba(240,191,85,.12),transparent 56%),rgba(5,14,12,.58)}.circle3-activation-visual:before,.circle3-activation-visual:after{position:absolute;inset:54px;border:1px solid rgba(246,242,232,.12);border-radius:50%;content:""}.circle3-activation-visual:after{inset:96px;border-color:rgba(91,214,232,.18)}.circle3-activation-visual span,.circle3-activation-visual strong{position:absolute;z-index:2;display:grid;place-items:center;text-align:center;font-family:var(--font-display);font-weight:950}.circle3-activation-visual span{width:112px;height:112px;border:1px solid rgba(246,242,232,.18);border-radius:50%;padding:14px;color:var(--soft);background:rgba(6,38,33,.92);font-size:.82rem}.circle3-activation-visual span:nth-child(1){left:50%;top:28px;transform:translateX(-50%)}.circle3-activation-visual span:nth-child(2){left:28px;bottom:42px}.circle3-activation-visual span:nth-child(3){right:28px;bottom:42px}.circle3-activation-visual strong{left:50%;top:50%;width:118px;height:118px;border-radius:30px;color:#07100e;background:linear-gradient(135deg,var(--gold),var(--mint));box-shadow:0 0 58px rgba(66,209,155,.24);transform:translate(-50%,-50%)}.circle3-activation-copy,.circle3-live-copy,.circle3-live-script{display:grid;gap:12px;border-radius:26px;padding:clamp(22px,4vw,34px)}.circle3-activation-copy{align-content:center;background:radial-gradient(circle at 90% 12%,rgba(91,214,232,.14),transparent 26%),var(--panel)}.circle3-activation-copy ul{display:grid;gap:9px;margin:0;padding-left:18px;color:var(--soft)}
      .circle3-room-types{display:grid;grid-template-columns:minmax(280px,1.1fr) repeat(3,minmax(0,1fr));gap:12px;margin-top:12px;border-radius:24px;padding:14px;background:radial-gradient(circle at 10% 18%,rgba(240,191,85,.1),transparent 24%),rgba(5,14,12,.42)}.circle3-room-types>div{display:grid;align-content:center;gap:10px;padding:12px}.circle3-room-types article{display:grid;gap:8px;border-radius:18px;padding:18px}.circle3-room-types h3,.circle3-room-types h4{margin:0}.circle3-live-script{align-content:center;min-height:260px;color:#07100e;background:radial-gradient(circle at 82% 20%,rgba(255,255,255,.42),transparent 24%),linear-gradient(135deg,var(--gold),var(--mint))}.circle3-live-script span,.circle3-live-script strong{font-family:var(--font-display);font-weight:950}.circle3-live-script span{font-size:clamp(1.8rem,3vw,3rem);line-height:1}.circle3-live-script strong{color:rgba(7,16,14,.72)}.circle3-live-script p{color:#07100e;font-size:clamp(1.05rem,1.8vw,1.35rem);font-weight:800}.circle3-roadmap{display:grid;gap:12px;margin-top:12px;border-radius:24px;padding:clamp(22px,4vw,34px);background:radial-gradient(circle at 85% 20%,rgba(240,191,85,.16),transparent 28%),radial-gradient(circle at 12% 70%,rgba(66,209,155,.12),transparent 28%),var(--panel)}.circle3-note{display:grid;grid-template-columns:auto minmax(260px,1fr) auto;gap:14px;align-items:center;margin-top:18px;border-radius:18px;padding:18px;background:linear-gradient(135deg,rgba(240,191,85,.1),rgba(66,209,155,.06)),var(--panel)}
      @media(max-width:980px){.circle3-grid,.circle3-saas-grid,.circle3-deep,.circle3-system,.circle3-activation,.circle3-live-room,.circle3-matrix,.circle3-infra{grid-template-columns:1fr}.circle3-pillars,.circle3-identity,.circle3-feature-board,.circle3-room-types{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media(max-width:640px){.circle3-pillars,.circle3-deep,.circle3-flow,.circle3-identity,.circle3-feature-board,.circle3-room-types,.circle3-matrix,.circle3-infra{grid-template-columns:1fr}.circle3-hero{min-height:auto}.circle3-orbit{min-height:260px}.circle3-activation-visual{min-height:340px}.circle3-activation-visual span:nth-child(1){top:16px}.circle3-activation-visual span:nth-child(2),.circle3-activation-visual span:nth-child(3){bottom:24px}.circle-person,.circle3-activation-visual span{width:88px;height:88px;font-size:.74rem}.circle3-activation-visual strong{width:96px;height:96px;border-radius:24px;font-size:.82rem}.circle3-note{grid-template-columns:1fr}}
    `;
    document.head.appendChild(style);
  };

  const enhance = (section) => {
    if (!section || section.querySelector(".circle3-activation")) return;
    const pillars = section.querySelector(".circle3-pillars");
    if (pillars) {
      pillars.insertAdjacentHTML("afterend", `
        <div class="circle3-deep" aria-label="Circle3 product brief"><article class="circle3-story-card"><p class="eyebrow">The problem</p><h3>Many young Muslims are surrounded by content, but still growing alone.</h3><p>Circle3 is designed for digital isolation, motivation crashes, inconsistent Salah and Qur'an routines, passive learning, and the missing feeling of trusted companionship. It gives the user a small circle that can be present without becoming noisy social media.</p><div class="circle3-tags"><span>Digital isolation</span><span>Habit inconsistency</span><span>Low accountability</span><span>Passive content</span></div></article><article class="circle3-story-card accent"><p class="eyebrow">The solution</p><h3>Three people, one guided room, one meaningful action each day.</h3><p>The system combines habit tracking, structured interaction, AI-generated prompts, and adab-first moderation. It is not Facebook, Discord, Telegram, or a lecture app. It becomes faith-centered micro-community infrastructure.</p><div class="circle3-tags"><span>Daily reflection</span><span>Islamic habits</span><span>Quiet support</span><span>Guided growth</span></div></article></div>
        <div class="circle3-system" aria-label="Circle3 architecture"><div class="circle3-system-copy"><p class="eyebrow">How Circle3 works</p><h3>Profile, match, prompt, practice, repeat.</h3><p>A user creates a simple profile, chooses Islamic and life goals, and receives a small circle built around compatibility.</p></div><div class="circle3-flow"><article><strong>01</strong><h4>User layer</h4><p>Nickname, gender, country, language, timezone, goals, personality, and habit focus.</p></article><article><strong>02</strong><h4>Matching engine</h4><p>Groups three members by age band, goals, timezone, language, activity, and interests.</p></article><article><strong>03</strong><h4>Daily room</h4><p>Fajr Warriors, Qur'an Consistency, Student Productivity, or Muslim Entrepreneurs.</p></article><article><strong>04</strong><h4>Growth loop</h4><p>Prompt, reflection, habit streak, silent presence, encouragement, and next action.</p></article></div></div>
        <div class="circle3-activation"><div class="circle3-activation-visual" aria-hidden="true"><span>Verified human</span><span>Verified human</span><span>Verified human</span><strong>Circle unlocks</strong></div><div class="circle3-activation-copy"><p class="eyebrow">Triadic activation engine</p><h3>Real conversations begin only when three real people are present.</h3><p>Circle3 unlocks chat, voice, habit sync, and the daily prompt only when three verified members enter the same room. Until then, users wait in a calm lobby.</p><ul><li>Three verified users required before a room becomes active.</li><li>Lobby mode keeps the experience quiet until the circle is complete.</li><li>Presence signals focus on safety, consent, and anti-abuse protection.</li></ul></div></div>
        <div class="circle3-identity"><article><span>01</span><h3>Mobile verification</h3><p>One phone number, one account, with OTP through Twilio, MSG91, or Firebase Auth.</p></article><article><span>02</span><h3>Liveness check</h3><p>A consent-based selfie or liveness check helps reduce fake accounts and bot circles.</p></article><article><span>03</span><h3>Device trust</h3><p>Device, IP, and browser risk signals protect from spam farms without exposing private details.</p></article><article><span>04</span><h3>Secure storage</h3><p>Encrypted storage, minimal retention, secure face embeddings, and clear user consent.</p></article></div>
        <div class="circle3-feature-board"><article><span>Prompt</span><h3>AI conversation starter</h3><p>Thoughtful, halal prompts such as what distracts you from consistency?</p></article><article><span>Track</span><h3>Habit accountability</h3><p>Salah, Qur'an minutes, dhikr, sleep, water, workout, detox, mood, streaks, and group progress.</p></article><article><span>Presence</span><h3>Silent companionship</h3><p>A user can say I am here silently and still receive the benefit of being part of a circle.</p></article><article><span>Future</span><h3>AI Islamic companion</h3><p>Premium habit coach, productivity mentor, Qur'an reflection assistant, and motivational responder.</p></article></div>
        <div class="circle3-room-types"><div><p class="eyebrow">Circle types</p><h3>Different rooms for different seasons of life.</h3></div><article><h4>Habit circles</h4><p>Fajr, Qur'an, productivity, fitness, fasting, dhikr, sleep, and social detox.</p></article><article><h4>Emotional support</h4><p>Loneliness, student pressure, stress, spiritual burnout, and gentle companionship.</p></article><article><h4>Intellectual circles</h4><p>Islamic philosophy, startup discussions, politics, AI, future tech, and Qur'anic science.</p></article></div>
        <div class="circle3-live-room"><div class="circle3-live-copy"><p class="eyebrow">Live room moment</p><h3>When all three arrive, the room begins with adab.</h3><p>The AI opens with a warm salam and a meaningful prompt. Energy matching balances active talkers, quiet listeners, shy users, and deeper intellectual users.</p></div><div class="circle3-live-script"><span>Assalamu Alaikum.</span><strong>Today's circle topic:</strong><p>What habit changed your life recently, and what made it easier to repeat?</p></div></div>
        <div class="circle3-matrix"><article><p class="eyebrow">Technical backbone</p><h3>Simple MVP stack</h3><p>Next.js, TailwindCSS, Supabase or Firebase, PostgreSQL, OpenAI API, local moderation, and realtime chat.</p></article><article><p class="eyebrow">Data model</p><h3>Small but scalable</h3><p>Users, circles, habits, prompt logs, activity score, engagement score, streaks, mood, and topic history.</p></article><article><p class="eyebrow">Trust layer</p><h3>Safety before growth</h3><p>Anti-harassment filters, gender separation options, AI moderation, spam protection, behavior scoring, and reporting.</p></article></div>
        <div class="circle3-infra"><article><p class="eyebrow">Phase 1</p><h3>Launch lean</h3><p>Vercel, Supabase or Firebase, PostgreSQL, Redis, WebSocket or Socket.IO, and AI moderation.</p></article><article><p class="eyebrow">Phase 2</p><h3>Scale toward millions</h3><p>AWS ECS or Kubernetes, Cloudflare, Redis cluster, CDN, vector database, and moderation services.</p></article><article><p class="eyebrow">Privacy promise</p><h3>Trust is the product</h3><p>Encrypted storage, parental protection, GDPR-style controls, and no public exposure of identity checks.</p></article></div>
      `);
    }
    const note = section.querySelector(".circle3-note");
    if (note && !section.querySelector(".circle3-roadmap")) {
      note.insertAdjacentHTML("beforebegin", `<div class="circle3-roadmap"><p class="eyebrow">Long-term vision</p><h3>A faith-centered real-human social operating system.</h3><p>Circle3 can grow into Muslim student circles, Qur'an memorization groups, startup founder circles, revert support, masjid integration, family habit systems, AI-guided Islamic wellness, and a global digital Ummah infrastructure layer.</p></div>`);
    }
  };

  const init = () => {
    addStyle();
    const section = document.getElementById(id);
    if (section) enhance(section);
  };

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
